services:
  - name: sudoku-backend
    type: web
    env: python
    buildCommand: pip install -r requirements.txt && python -m flask db upgrade
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dbsudoku
          property: connectionString
      - key: FLASK_ENV
        value: production

databases:
  - name: dbsudoku
    plan: free
    databaseName: dbsudoku
    user: sudoku_user